import { useState } from "react";
import Layout from "@/components/layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  FileText, Plus, Trash2, Download, Eye, Loader2, CheckCircle, XCircle,
  BarChart3, Shield, AlertTriangle, Database, FileBarChart, ClipboardList,
  Clock, Calendar
} from "lucide-react";
import { motion } from "framer-motion";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import type { Report } from "@shared/schema";
import { HelpIcon } from "@/components/help-icon";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { getFyxLogoAsImage } from "@/lib/fyx-logo-data";

const COLORS = {
  header: "#007aff",
  critical: "#ef4444",
  high: "#f97316",
  medium: "#eab308",
  low: "#22c55e",
  info: "#6b7280",
};

function hexToRgb(hex: string): [number, number, number] {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

function severityColor(severity: string): [number, number, number] {
  const map: Record<string, string> = {
    Critical: COLORS.critical, critical: COLORS.critical,
    High: COLORS.high, high: COLORS.high,
    Medium: COLORS.medium, medium: COLORS.medium,
    Low: COLORS.low, low: COLORS.low,
    Info: COLORS.info, info: COLORS.info,
  };
  return hexToRgb(map[severity] || COLORS.info);
}

function addPdfHeader(doc: jsPDF, report: Report, logoDataUrl?: string) {
  const data = report.data as Record<string, any>;
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(235, 243, 255);
  doc.rect(0, 0, pageWidth, 44, "F");

  doc.setDrawColor(200, 220, 250);
  doc.setLineWidth(0.3);
  doc.line(0, 44, pageWidth, 44);

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", 14, 6, 13, 13);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 82, 186);
  doc.text("FYX CLOUD", 30, 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("AI Security Posture Management", 30, 21);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text(report.name || "Report", 14, 32);

  const typeLabel = reportTypeConfig[report.type]?.label || report.type;
  const genDate = data.generatedAt ? new Date(data.generatedAt).toLocaleString() : new Date().toLocaleString();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`${typeLabel}  \u2022  ${genDate}  \u2022  Generated by: ${report.generatedBy || "System"}`, 14, 38);

  const confTag = "CONFIDENTIAL";
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255);
  const confW = doc.getTextWidth(confTag) + 6;
  doc.setFillColor(220, 38, 38);
  doc.roundedRect(pageWidth - 14 - confW, 9, confW, 7, 1.5, 1.5, "F");
  doc.text(confTag, pageWidth - 14 - confW + 3, 14);

  return 52;
}

function addPdfFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const timestamp = new Date().toLocaleString();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setDrawColor(200, 200, 210);
    doc.setLineWidth(0.2);
    doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);

    doc.setFillColor(...hexToRgb(COLORS.header));
    doc.rect(14, pageHeight - 13, 2, 5, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(...hexToRgb(COLORS.header));
    doc.text("Fyx Cloud", 18, pageHeight - 9.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Fyx Cloud AI-SPM  |  Confidential", 34, pageHeight - 9.5);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.text(timestamp, pageWidth / 2, pageHeight - 9.5, { align: "center" });

    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 9.5, { align: "right" });
  }
}

function addSectionHeading(doc: jsPDF, title: string, y: number): number {
  if (y > doc.internal.pageSize.getHeight() - 30) {
    doc.addPage();
    y = 20;
  }
  doc.setFillColor(...hexToRgb(COLORS.header));
  doc.rect(14, y - 4, 3, 10, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 50);
  doc.text(title.toUpperCase(), 20, y + 3);

  doc.setDrawColor(220, 225, 235);
  doc.setLineWidth(0.2);
  doc.line(14, y + 6, doc.internal.pageSize.getWidth() - 14, y + 6);
  return y + 12;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > doc.internal.pageSize.getHeight() - 20) {
    doc.addPage();
    return 20;
  }
  return y;
}

async function generateReportPDF(report: Report) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const data = report.data as Record<string, any>;
  if (!data) return;

  let logoDataUrl: string | undefined;
  try {
    logoDataUrl = await getFyxLogoAsImage();
  } catch {}

  let y = addPdfHeader(doc, report, logoDataUrl);

  if (data.summary) {
    y = addSectionHeading(doc, "Executive Summary", y);
    const entries = Object.entries(data.summary);
    const colWidth = (doc.internal.pageSize.getWidth() - 28) / Math.min(entries.length, 4);
    const rows = Math.ceil(entries.length / 4);

    for (let row = 0; row < rows; row++) {
      y = checkPageBreak(doc, y, 18);
      const rowEntries = entries.slice(row * 4, (row + 1) * 4);
      rowEntries.forEach(([key, value], i) => {
        const xPos = 14 + i * colWidth;
        doc.setFillColor(248, 250, 252);
        doc.setDrawColor(230, 235, 245);
        doc.roundedRect(xPos, y - 2, colWidth - 3, 16, 1.5, 1.5, "FD");

        doc.setFont("helvetica", "normal");
        doc.setFontSize(6.5);
        doc.setTextColor(120, 120, 130);
        const label = key.replace(/([A-Z])/g, " $1").trim();
        doc.text(label.charAt(0).toUpperCase() + label.slice(1), xPos + 3, y + 3);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(30, 30, 50);
        doc.text(String(value), xPos + 3, y + 11);
      });
      y += 20;
    }
    y += 2;
  }

  if (data.severityBreakdown) {
    y = addSectionHeading(doc, "Severity Breakdown", y);
    y = checkPageBreak(doc, y, 40);
    const entries = typeof data.severityBreakdown === "object" && !Array.isArray(data.severityBreakdown)
      ? Object.entries(data.severityBreakdown)
      : (data.severityBreakdown as any[]).map((s: any) => [s.severity, s.count]);

    const maxCount = Math.max(...entries.map(([, c]) => Number(c) || 1), 1);
    const barMaxWidth = doc.internal.pageSize.getWidth() - 80;

    doc.setFillColor(248, 248, 252);
    doc.roundedRect(14, y - 3, doc.internal.pageSize.getWidth() - 28, entries.length * 9 + 8, 2, 2, "F");
    doc.setDrawColor(230, 230, 240);
    doc.roundedRect(14, y - 3, doc.internal.pageSize.getWidth() - 28, entries.length * 9 + 8, 2, 2, "S");

    entries.forEach(([sev, count]) => {
      const numCount = Number(count) || 0;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...severityColor(String(sev)));
      doc.text(`${sev}`, 18, y + 3);

      const barWidth = (numCount / maxCount) * barMaxWidth;
      doc.setFillColor(...severityColor(String(sev)));
      if (barWidth > 0) {
        doc.roundedRect(48, y - 1, Math.max(barWidth, 2), 5, 1, 1, "F");
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(60, 60, 60);
      doc.text(String(count), 48 + barWidth + 3, y + 3);
      y += 9;
    });
    y += 8;
  }

  if (data.statusBreakdown) {
    y = addSectionHeading(doc, "Status Breakdown", y);
    const entries = typeof data.statusBreakdown === "object" && !Array.isArray(data.statusBreakdown)
      ? Object.entries(data.statusBreakdown)
      : (data.statusBreakdown as any[]).map((s: any) => [s.status, s.count]);
    entries.forEach(([status, count]) => {
      y = checkPageBreak(doc, y, 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`${String(status)}:`, 16, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(String(count), 55, y);
      y += 6;
    });
    y += 4;
  }

  if (data.categoryBreakdown) {
    y = addSectionHeading(doc, "Category Breakdown", y);
    const entries = typeof data.categoryBreakdown === "object" && !Array.isArray(data.categoryBreakdown)
      ? Object.entries(data.categoryBreakdown)
      : (data.categoryBreakdown as any[]).map((c: any) => [c.category, c.count]);
    autoTable(doc, {
      startY: y,
      head: [["Category", "Count"]],
      body: entries.map(([cat, count]) => [String(cat), String(count)]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 8 },
      bodyStyles: { font: "helvetica", fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.topFindings && data.topFindings.length > 0) {
    y = addSectionHeading(doc, "Top Findings", y);
    autoTable(doc, {
      startY: y,
      head: [["#", "Finding", "Severity", "Asset", "Rule ID"]],
      body: data.topFindings.map((f: any, i: number) => [
        String(i + 1),
        String(f.finding || "").substring(0, 60),
        f.severity,
        f.assetName || "",
        f.ruleId || "",
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 8 },
      bodyStyles: { font: "helvetica", fontSize: 7 },
      columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 70 }, 2: { cellWidth: 20 }, 3: { cellWidth: 40 }, 4: { cellWidth: 22 } },
      margin: { left: 14, right: 14 },
      didParseCell: (hookData: any) => {
        if (hookData.section === "body" && hookData.column.index === 2) {
          hookData.cell.styles.textColor = severityColor(hookData.cell.raw as string);
          hookData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.frameworks && data.frameworks.length > 0) {
    y = addSectionHeading(doc, "Compliance Frameworks", y);
    autoTable(doc, {
      startY: y,
      head: [["Framework", "Compliance %", "Passed", "Failed", "Total"]],
      body: data.frameworks.map((fw: any) => [
        fw.name,
        `${fw.complianceRate}%`,
        String(fw.passedControls),
        String(fw.failedControls),
        String(fw.totalControls),
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 8 },
      bodyStyles: { font: "helvetica", fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.topRiskAssets && data.topRiskAssets.length > 0) {
    y = addSectionHeading(doc, "Top Risk Assets", y);
    autoTable(doc, {
      startY: y,
      head: [["#", "Asset Name", "Type", "Findings", "Critical", "High", "Risk Score"]],
      body: data.topRiskAssets.slice(0, 20).map((a: any, i: number) => [
        String(i + 1),
        a.name || "",
        a.type || "",
        String(a.findings || 0),
        String(a.criticalCount || 0),
        String(a.highCount || 0),
        String(a.riskScore || 0),
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 8 },
      bodyStyles: { font: "helvetica", fontSize: 7 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.findings && Array.isArray(data.findings) && data.findings.length > 0) {
    y = addSectionHeading(doc, "Finding Details", y);
    autoTable(doc, {
      startY: y,
      head: [["Rule ID", "Finding", "Severity", "Status", "Asset", "Detected"]],
      body: data.findings.slice(0, 100).map((f: any) => [
        f.ruleId || "",
        String(f.finding || "").substring(0, 50),
        f.severity || "",
        f.status || "",
        f.assetName || "",
        f.detectedAt ? new Date(f.detectedAt).toLocaleDateString() : "",
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 7 },
      bodyStyles: { font: "helvetica", fontSize: 6 },
      margin: { left: 14, right: 14 },
      didParseCell: (hookData: any) => {
        if (hookData.section === "body" && hookData.column.index === 2) {
          hookData.cell.styles.textColor = severityColor(hookData.cell.raw as string);
          hookData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.resources && Array.isArray(data.resources) && data.resources.length > 0) {
    y = addSectionHeading(doc, "Resources", y);
    autoTable(doc, {
      startY: y,
      head: [["Name", "Type", "Category", "Risk", "Exposure"]],
      body: data.resources.slice(0, 100).map((r: any) => [
        r.name || "",
        r.type || "",
        r.category || "",
        r.risk || "",
        r.exposure || "",
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 7 },
      bodyStyles: { font: "helvetica", fontSize: 6 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.models && Array.isArray(data.models) && data.models.length > 0) {
    y = addSectionHeading(doc, "AI Models", y);
    autoTable(doc, {
      startY: y,
      head: [["Name", "Type", "Category", "Status", "Risk Score"]],
      body: data.models.map((m: any) => [
        m.name || "",
        m.type || "",
        m.category || "",
        m.status || "",
        String(m.riskScore || 0),
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 8 },
      bodyStyles: { font: "helvetica", fontSize: 7 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.categoryCoverage) {
    y = addSectionHeading(doc, "Category Coverage", y);
    const entries = typeof data.categoryCoverage === "object" && !Array.isArray(data.categoryCoverage)
      ? Object.entries(data.categoryCoverage).map(([cat, info]: [string, any]) => [cat, String(info.enabled || 0), String(info.total || 0), String(info.withFindings || 0)])
      : (data.categoryCoverage as any[]).map((c: any) => [c.category, String(c.enabledPolicies || 0), String(c.totalFindings || 0)]);
    const isObj = typeof data.categoryCoverage === "object" && !Array.isArray(data.categoryCoverage);
    autoTable(doc, {
      startY: y,
      head: [isObj ? ["Category", "Enabled", "Total", "With Findings"] : ["Category", "Enabled Policies", "Total Findings"]],
      body: entries,
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 8 },
      bodyStyles: { font: "helvetica", fontSize: 7 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.riskBreakdown) {
    y = addSectionHeading(doc, "Risk Breakdown", y);
    y = checkPageBreak(doc, y, 40);
    const entries = Object.entries(data.riskBreakdown);
    const maxCount = Math.max(...entries.map(([, c]) => Number(c) || 1), 1);
    const barMaxWidth = doc.internal.pageSize.getWidth() - 80;

    doc.setFillColor(248, 248, 252);
    doc.roundedRect(14, y - 3, doc.internal.pageSize.getWidth() - 28, entries.length * 9 + 8, 2, 2, "F");
    doc.setDrawColor(230, 230, 240);
    doc.roundedRect(14, y - 3, doc.internal.pageSize.getWidth() - 28, entries.length * 9 + 8, 2, 2, "S");

    entries.forEach(([risk, count]) => {
      const numCount = Number(count) || 0;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...severityColor(risk));
      doc.text(`${risk}`, 18, y + 3);

      const barWidth = (numCount / maxCount) * barMaxWidth;
      doc.setFillColor(...severityColor(risk));
      if (barWidth > 0) {
        doc.roundedRect(48, y - 1, Math.max(barWidth, 2), 5, 1, 1, "F");
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(60, 60, 60);
      doc.text(String(count), 48 + barWidth + 3, y + 3);
      y += 9;
    });
    y += 8;
  }

  if (data.policies && Array.isArray(data.policies) && data.policies.length > 0) {
    y = addSectionHeading(doc, "Policies", y);
    autoTable(doc, {
      startY: y,
      head: [["Rule ID", "Name", "Category", "Severity", "Enabled", "Open", "Resolved"]],
      body: data.policies.slice(0, 100).map((p: any) => [
        p.ruleId || "",
        String(p.name || "").substring(0, 40),
        p.category || "",
        p.severity || "",
        p.enabled ? "Yes" : "No",
        String(p.openFindings || 0),
        String(p.resolvedFindings || 0),
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 7 },
      bodyStyles: { font: "helvetica", fontSize: 6 },
      margin: { left: 14, right: 14 },
      didParseCell: (hookData: any) => {
        if (hookData.section === "body" && hookData.column.index === 3) {
          hookData.cell.styles.textColor = severityColor(hookData.cell.raw as string);
          hookData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.allComplianceFindings && data.allComplianceFindings.length > 0) {
    y = addSectionHeading(doc, "All Compliance Findings", y);
    autoTable(doc, {
      startY: y,
      head: [["Rule ID", "Finding", "Severity", "Status", "Asset", "Detected"]],
      body: data.allComplianceFindings.slice(0, 100).map((f: any) => [
        f.ruleId || "",
        String(f.finding || "").substring(0, 50),
        f.severity || "",
        f.status || "",
        f.assetName || "",
        f.detectedAt ? new Date(f.detectedAt).toLocaleDateString() : "",
      ]),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(COLORS.header), font: "helvetica", fontStyle: "bold", fontSize: 7 },
      bodyStyles: { font: "helvetica", fontSize: 6 },
      margin: { left: 14, right: 14 },
    });
  }

  addPdfFooters(doc);

  const fileName = `${(report.name || "report").replace(/[^a-zA-Z0-9]/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(fileName);
}

const reportTypeConfig: Record<string, { label: string; icon: typeof FileText; color: string; description: string }> = {
  executive_summary: { label: "Executive Summary", icon: BarChart3, color: "text-blue-400 bg-blue-500/10", description: "High-level overview of security posture, risk scores, and key metrics" },
  compliance: { label: "Compliance Report", icon: Shield, color: "text-violet-400 bg-violet-500/10", description: "Framework compliance status for EU AI Act, NIST AI RMF, SOC 2, and GDPR" },
  risk_assessment: { label: "Risk Assessment", icon: AlertTriangle, color: "text-amber-400 bg-amber-500/10", description: "Detailed risk analysis of assets with prioritized remediation guidance" },
  finding_detail: { label: "Finding Detail", icon: ClipboardList, color: "text-red-400 bg-red-500/10", description: "Complete list of all findings with impact, remediation, and evidence" },
  asset_inventory: { label: "Asset Inventory", icon: Database, color: "text-cyan-400 bg-cyan-500/10", description: "Full inventory of all monitored resources and AI models" },
  policy_coverage: { label: "Policy Coverage", icon: FileBarChart, color: "text-emerald-400 bg-emerald-500/10", description: "Policy enablement status and finding distribution across categories" },
};

const statusBadge: Record<string, { color: string; label: string }> = {
  generating: { color: "bg-amber-500/10 text-amber-400 border-amber-500/20", label: "Generating" },
  completed: { color: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", label: "Completed" },
  failed: { color: "bg-red-500/10 text-red-400 border-red-500/20", label: "Failed" },
};

export default function ReportsPage() {
  const [generateOpen, setGenerateOpen] = useState(false);
  const [viewReport, setViewReport] = useState<Report | null>(null);
  const [form, setForm] = useState({
    type: "executive_summary",
    name: "",
    dateRange: "30d",
  });
  const { toast } = useToast();

  const { data: reportsList = [], isLoading } = useQuery<Report[]>({
    queryKey: ["/api/reports"],
    refetchInterval: 5000,
  });

  const generateMut = useMutation({
    mutationFn: (data: any) => apiRequest("POST", "/api/reports/generate", data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/reports"] });
      setGenerateOpen(false);
      setForm({ type: "executive_summary", name: "", dateRange: "30d" });
      toast({ title: "Report generation started", variant: "success" });
    },
    onError: () => toast({ title: "Failed to generate report", variant: "destructive" }),
  });

  const deleteMut = useMutation({
    mutationFn: (id: string) => apiRequest("DELETE", `/api/reports/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/reports"] });
      toast({ title: "Report deleted", variant: "success" });
    },
  });

  const viewMut = useMutation({
    mutationFn: (id: string) => apiRequest("GET", `/api/reports/${id}`).then(r => r.json()),
    onSuccess: (data: Report) => setViewReport(data),
  });

  function handleGenerate() {
    const config = reportTypeConfig[form.type];
    const name = form.name || `${config.label} - ${new Date().toLocaleDateString()}`;
    generateMut.mutate({
      type: form.type,
      name,
      filters: { dateRange: form.dateRange },
    });
  }

  return (
    <Layout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2" data-testid="text-reports-title">Reports <HelpIcon section="reports" /></h1>
            <p className="text-sm text-muted-foreground mt-1">
              Generate and manage security reports
            </p>
          </div>
          <Button className="gap-2 bg-[#007aff] hover:bg-[#0066d6] text-white" onClick={() => setGenerateOpen(true)} data-testid="button-generate-report">
            <Plus className="h-4 w-4" />
            Generate Report
          </Button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { label: "Total Reports", value: reportsList.length, icon: FileText, color: "text-[#007aff]" },
            { label: "Completed", value: reportsList.filter(r => r.status === "completed").length, icon: CheckCircle, color: "text-emerald-400" },
            { label: "Generating", value: reportsList.filter(r => r.status === "generating").length, icon: Clock, color: "text-amber-400" },
          ].map((stat) => (
            <Card key={stat.label} className="glass-panel border-border/50 bg-card/50 backdrop-blur-sm">
              <CardContent className="p-4 flex items-center gap-4">
                <div className={`h-10 w-10 rounded-lg flex items-center justify-center bg-muted/30 ${stat.color}`}>
                  <stat.icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stat.value}</p>
                  <p className="text-xs text-muted-foreground">{stat.label}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <Card className="glass-panel border-border/50 bg-card/50 backdrop-blur-sm">
          <CardHeader className="pb-3">
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-[#007aff]" />
              <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">GENERATED REPORTS</span>
            </div>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : reportsList.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <FileText className="h-10 w-10 mb-3 opacity-30" />
                <p className="text-sm font-medium">No reports generated yet</p>
                <p className="text-xs mt-1">Generate your first report to get started</p>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow className="border-border/50">
                    <TableHead className="text-xs">Report</TableHead>
                    <TableHead className="text-xs">Type</TableHead>
                    <TableHead className="text-xs">Status</TableHead>
                    <TableHead className="text-xs">Generated By</TableHead>
                    <TableHead className="text-xs">Date</TableHead>
                    <TableHead className="text-xs text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {reportsList.map((report) => {
                    const typeConf = reportTypeConfig[report.type] || reportTypeConfig.executive_summary;
                    const statusConf = statusBadge[report.status] || statusBadge.generating;
                    const TypeIcon = typeConf.icon;
                    return (
                      <TableRow key={report.id} className="border-border/30 hover:bg-muted/20" data-testid={`row-report-${report.id}`}>
                        <TableCell>
                          <div className="flex items-center gap-3">
                            <div className={`h-8 w-8 rounded-lg flex items-center justify-center ${typeConf.color}`}>
                              <TypeIcon className="h-4 w-4" />
                            </div>
                            <span className="font-medium text-sm">{report.name}</span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline" className="text-[10px]">{typeConf.label}</Badge>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline" className={`text-[10px] ${statusConf.color}`}>
                            {report.status === "generating" && <Loader2 className="h-3 w-3 animate-spin mr-1" />}
                            {statusConf.label}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-xs text-muted-foreground">{report.generatedBy}</TableCell>
                        <TableCell className="text-xs text-muted-foreground">
                          {report.generatedAt ? new Date(report.generatedAt).toLocaleDateString() : "—"}
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center justify-end gap-1">
                            {report.status === "completed" && (
                              <>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-7 w-7 text-muted-foreground hover:text-[#007aff]"
                                  onClick={() => viewMut.mutate(report.id)}
                                  data-testid={`button-view-report-${report.id}`}
                                >
                                  <Eye className="h-3.5 w-3.5" />
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-7 w-7 text-muted-foreground hover:text-[#007aff]"
                                  onClick={async () => {
                                    try {
                                      const res = await apiRequest("GET", `/api/reports/${report.id}`);
                                      const fullReport = await res.json();
                                      generateReportPDF(fullReport);
                                      toast({ title: "PDF exported successfully", variant: "success" });
                                    } catch {
                                      toast({ title: "Failed to export PDF", variant: "destructive" });
                                    }
                                  }}
                                  data-testid={`button-export-pdf-${report.id}`}
                                >
                                  <Download className="h-3.5 w-3.5" />
                                </Button>
                              </>
                            )}
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-7 w-7 text-muted-foreground hover:text-destructive"
                              onClick={() => deleteMut.mutate(report.id)}
                              data-testid={`button-delete-report-${report.id}`}
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>

        {/* Generate Report Sheet */}
        <Sheet open={generateOpen} onOpenChange={setGenerateOpen}>
          <SheetContent className="w-full sm:w-[50vw] sm:max-w-[50vw] bg-card/95 backdrop-blur-xl border-l border-border overflow-y-auto">
            <SheetHeader>
              <SheetTitle className="text-lg font-bold">Generate Report</SheetTitle>
            </SheetHeader>

            <div className="space-y-6 mt-6">
              <div className="space-y-3">
                <Label className="text-xs font-semibold text-primary/70 uppercase tracking-wider">Report Type</Label>
                <div className="grid grid-cols-1 gap-2">
                  {Object.entries(reportTypeConfig).map(([key, config]) => {
                    const Icon = config.icon;
                    return (
                      <button
                        key={key}
                        type="button"
                        className={`flex items-center gap-3 p-3 rounded-lg border transition-all text-left ${
                          form.type === key
                            ? "border-[#007aff] bg-[#007aff]/10 ring-1 ring-[#007aff]/30"
                            : "border-border/50 hover:border-border hover:bg-muted/30"
                        }`}
                        onClick={() => setForm(prev => ({ ...prev, type: key }))}
                        data-testid={`button-report-type-${key}`}
                      >
                        <div className={`h-9 w-9 rounded-lg flex items-center justify-center ${config.color}`}>
                          <Icon className="h-4.5 w-4.5" />
                        </div>
                        <div>
                          <p className="text-sm font-medium">{config.label}</p>
                          <p className="text-[11px] text-muted-foreground">{config.description}</p>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>

              <Separator className="bg-border/50" />

              <div className="space-y-4">
                <div className="space-y-1.5">
                  <Label className="text-xs">Report Name (optional)</Label>
                  <Input
                    value={form.name}
                    onChange={e => setForm(prev => ({ ...prev, name: e.target.value }))}
                    placeholder={`${reportTypeConfig[form.type]?.label} - ${new Date().toLocaleDateString()}`}
                    className="bg-muted/30 border-border/50"
                    data-testid="input-report-name"
                  />
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs">Time Range</Label>
                  <Select value={form.dateRange} onValueChange={v => setForm(prev => ({ ...prev, dateRange: v }))}>
                    <SelectTrigger className="bg-muted/30 border-border/50" data-testid="select-date-range">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="7d">Last 7 days</SelectItem>
                      <SelectItem value="14d">Last 14 days</SelectItem>
                      <SelectItem value="30d">Last 30 days</SelectItem>
                      <SelectItem value="60d">Last 60 days</SelectItem>
                      <SelectItem value="90d">Last 90 days</SelectItem>
                      <SelectItem value="all">All time</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="flex gap-2 pt-4">
                <Button variant="outline" className="flex-1" onClick={() => setGenerateOpen(false)}>
                  Cancel
                </Button>
                <Button
                  className="flex-1 bg-[#007aff] hover:bg-[#0066d6] text-white gap-2"
                  onClick={handleGenerate}
                  disabled={generateMut.isPending}
                  data-testid="button-submit-generate"
                >
                  {generateMut.isPending && <Loader2 className="h-4 w-4 animate-spin" />}
                  Generate Report
                </Button>
              </div>
            </div>
          </SheetContent>
        </Sheet>

        {/* View Report Sheet */}
        <Sheet open={!!viewReport} onOpenChange={(open) => !open && setViewReport(null)}>
          <SheetContent className="w-full sm:w-[50vw] sm:max-w-[50vw] bg-card/95 backdrop-blur-xl border-l border-border overflow-y-auto">
            <SheetHeader>
              <div className="flex items-center justify-between">
                <SheetTitle className="text-lg font-bold">{viewReport?.name}</SheetTitle>
                {viewReport && viewReport.status === "completed" && (
                  <Button
                    className="gap-2 bg-[#007aff] hover:bg-[#0066d6] text-white"
                    size="sm"
                    onClick={() => generateReportPDF(viewReport)}
                    data-testid="button-export-pdf"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Export PDF
                  </Button>
                )}
              </div>
            </SheetHeader>

            {viewReport && (
              <ScrollArea className="mt-6 h-[calc(100vh-120px)]">
                <ReportViewer report={viewReport} />
              </ScrollArea>
            )}
          </SheetContent>
        </Sheet>
      </div>
    </Layout>
  );
}

function ReportViewer({ report }: { report: Report }) {
  const data = report.data as Record<string, any>;
  if (!data || data.error) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
        <XCircle className="h-8 w-8 mb-2 text-red-400" />
        <p className="text-sm">{data?.error || "Report data unavailable"}</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 pr-4">
      <div className="p-4 rounded-lg bg-muted/20 border border-border/30">
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Report Details</span>
          <Badge variant="outline" className="text-[10px]">{data.reportType || report.type}</Badge>
        </div>
        <div className="grid grid-cols-2 gap-2 text-xs">
          <div><span className="text-muted-foreground">Generated:</span> <span className="font-medium">{data.generatedAt ? new Date(data.generatedAt).toLocaleString() : "—"}</span></div>
          <div><span className="text-muted-foreground">By:</span> <span className="font-medium">{report.generatedBy}</span></div>
        </div>
      </div>

      {data.summary && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Summary</span>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {Object.entries(data.summary).map(([key, value]) => (
              <div key={key} className="p-3 rounded-lg bg-muted/20 border border-border/30">
                <p className="text-xs text-muted-foreground capitalize">{key.replace(/([A-Z])/g, " $1").trim()}</p>
                <p className="text-lg font-bold mt-1">{String(value)}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.severityBreakdown && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Severity Breakdown</span>
          <div className="flex gap-2">
            {Object.entries(data.severityBreakdown).map(([sev, count]) => {
              const colors: Record<string, string> = {
                Critical: "bg-red-500/10 text-red-400 border-red-500/20",
                High: "bg-blue-500/10 text-blue-400 border-blue-500/20",
                Medium: "bg-amber-500/10 text-amber-400 border-amber-500/20",
                Low: "bg-blue-500/10 text-blue-400 border-blue-500/20",
                Info: "bg-gray-500/10 text-gray-400 border-gray-500/20",
              };
              return (
                <div key={sev} className={`flex-1 p-3 rounded-lg border ${colors[sev] || ""}`}>
                  <p className="text-xs">{sev}</p>
                  <p className="text-xl font-bold mt-1">{String(count)}</p>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {data.frameworks && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Compliance Frameworks</span>
          <div className="space-y-2">
            {data.frameworks.map((fw: any) => (
              <div key={fw.name} className="p-3 rounded-lg bg-muted/20 border border-border/30">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-semibold">{fw.name}</span>
                  <Badge variant="outline" className={`text-[10px] ${fw.complianceRate >= 80 ? "text-emerald-400 border-emerald-500/20" : fw.complianceRate >= 50 ? "text-amber-400 border-amber-500/20" : "text-red-400 border-red-500/20"}`}>
                    {fw.complianceRate}% Compliant
                  </Badge>
                </div>
                <div className="h-2 rounded-full bg-muted/50 overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all ${fw.complianceRate >= 80 ? "bg-emerald-500" : fw.complianceRate >= 50 ? "bg-amber-500" : "bg-red-500"}`}
                    style={{ width: `${fw.complianceRate}%` }}
                  />
                </div>
                <div className="flex gap-4 mt-2 text-xs text-muted-foreground">
                  <span>{fw.passedControls} passed</span>
                  <span>{fw.failedControls} failed</span>
                  <span>{fw.totalControls} total controls</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.topFindings && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Top Open Findings</span>
          <div className="space-y-1">
            {data.topFindings.map((f: any, i: number) => {
              const sevColors: Record<string, string> = {
                Critical: "text-red-400",
                High: "text-blue-400",
                Medium: "text-amber-400",
                Low: "text-blue-400",
              };
              return (
                <div key={f.id || i} className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-muted/20 border border-border/20">
                  <span className={`text-xs font-bold w-6 ${sevColors[f.severity] || ""}`}>{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm truncate">{f.finding}</p>
                    <p className="text-[10px] text-muted-foreground">{f.assetName} · {f.ruleId}</p>
                  </div>
                  <Badge variant="outline" className={`text-[10px] shrink-0 ${sevColors[f.severity] || ""}`}>{f.severity}</Badge>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {data.topRiskAssets && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Top Risk Assets</span>
          <div className="space-y-1">
            {data.topRiskAssets.slice(0, 10).map((a: any, i: number) => (
              <div key={i} className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-muted/20 border border-border/20">
                <span className="text-xs font-bold w-6 text-muted-foreground">{i + 1}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm truncate">{a.name}</p>
                  <p className="text-[10px] text-muted-foreground">{a.type} · {a.findings} findings</p>
                </div>
                <div className="text-right">
                  <p className="text-sm font-bold">{a.riskScore}</p>
                  <p className="text-[10px] text-muted-foreground">risk score</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.categoryCoverage && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Category Coverage</span>
          <div className="space-y-2">
            {Object.entries(data.categoryCoverage).map(([cat, info]: [string, any]) => (
              <div key={cat} className="flex items-center gap-3 p-2.5 rounded-lg bg-muted/20 border border-border/30">
                <span className="text-sm font-medium w-24">{cat}</span>
                <div className="flex-1 h-2 rounded-full bg-muted/50 overflow-hidden">
                  <div className="h-full bg-[#007aff] rounded-full" style={{ width: `${(info.enabled / info.total) * 100}%` }} />
                </div>
                <span className="text-xs text-muted-foreground w-20 text-right">{info.enabled}/{info.total} enabled</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.categoryBreakdown && !data.categoryCoverage && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Category Distribution</span>
          <div className="grid grid-cols-2 gap-2">
            {Object.entries(data.categoryBreakdown).map(([cat, count]) => (
              <div key={cat} className="p-3 rounded-lg bg-muted/20 border border-border/30">
                <p className="text-xs text-muted-foreground">{cat}</p>
                <p className="text-lg font-bold mt-1">{String(count)}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.riskBreakdown && (
        <div className="space-y-3">
          <span className="text-[10px] font-semibold tracking-[0.15em] text-primary/60 uppercase">Risk Breakdown</span>
          <div className="flex gap-2">
            {Object.entries(data.riskBreakdown).map(([risk, count]) => {
              const colors: Record<string, string> = {
                Critical: "bg-red-500/10 text-red-400 border-red-500/20",
                High: "bg-blue-500/10 text-blue-400 border-blue-500/20",
                Medium: "bg-amber-500/10 text-amber-400 border-amber-500/20",
                Low: "bg-blue-500/10 text-blue-400 border-blue-500/20",
              };
              return (
                <div key={risk} className={`flex-1 p-3 rounded-lg border ${colors[risk] || ""}`}>
                  <p className="text-xs">{risk}</p>
                  <p className="text-xl font-bold mt-1">{String(count)}</p>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
